"""Initial migration

Revision ID: 1dea9da9b9cc
Revises: 
Create Date: 2024-12-18 22:46:45.341686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dea9da9b9cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chains',
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('chain', sa.String(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('actived', sa.Boolean(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('activate',
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('till', sa.DateTime(), nullable=False),
    sa.Column('actived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallets',
    sa.Column('address', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=26), nullable=False),
    sa.Column('chain_id', sa.String(length=26), nullable=False),
    sa.Column('mnemonic', sa.String(), nullable=False),
    sa.Column('tag', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chain_id'], ['chains.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('mnemonic')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallets')
    op.drop_table('activate')
    op.drop_table('users')
    op.drop_table('chains')
    # ### end Alembic commands ###
